Move manifest logo outside of root level.
Apparantly the plugin can not handle the location in content/Assets/.
Might be due to case sensitivity.

Cannot read property 'match' of undefined

  TypeError: Cannot read property 'match' of undefined

  - api-runner-node-error-parser.js:39 errorParser
    [django-de-v5]/[gatsby]/dist/utils/api-runner-node-error-parser.js:39:33

  - api-runner-node.js:398
    [django-de-v5]/[gatsby]/dist/utils/api-runner-node.js:398:29

  - api-runner-node.js:340 async module.exports
    [django-de-v5]/[gatsby]/dist/utils/api-runner-node.js:340:18

  - index.js:507 async module.exports
    [django-de-v5]/[gatsby]/dist/bootstrap/index.js:507:3

  - build.js:72 async build
    [django-de-v5]/[gatsby]/dist/commands/build.js:72:7

not finished onPostBootstrap - 0.035s
not finished Build manifest and related icons - 0.038s
npm ERR! code ELIFECYCLE